### ISSUE TITLE
Vanilla Deployment: on Rocky 9

### ISSUE THREAD

**Issue by kmf** [ctrliq/ascender-install#27]
```
TASK [ascender_install : Create Namespace] ********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.kubernetes.core.plugins.module_utils.k8s.exceptions.CoreException: Could not create API client: Invalid kube-config file. No configuration found.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not create API client: Invalid kube-config file. No configuration found."}
```

**Comment by cigamit** [comment]
We are going to need a little more information.

Do you already have Kubernetes installed?

- If yes, on the machine running the installer, do you have a kubeconf file at ~/.kube/config
- If no, and you want k3s installed, did you set the flag in default.config.yml "kube_install: true"

**Comment by kmf** [comment]
I'll get back to you.

**Comment by kmf** [comment]
My mistake didn't set the value `"kube_install: true"`

**Comment by kmf** [comment]
I think the default behaviour should be to install k8s by default, which was the expectation.

**Comment by cigamit** [comment]
Some people have their own k8s install, and we don't want to accidently cause issues if we attempt to install k3s over top of their k8s.  So it was safest to leave it off.  I do think we should move it closer to the top so it is easier to find though.

Did it otherwise complete successfully?

**Comment by kmf** [comment]
worked like a charm™
