### ISSUE TITLE
Rocky 8.8: Credential error for task 'Disable the Next UI'

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [ctrliq/ascender-install#37]
Hi,

While following the CIQ Blog post [Ascender VM Basic Install Guide (Utilizes K3s)](https://ciq.com/blog/ascender-vm-basic-install-guide-utilizes-k3s/), Ascender successfully installed but did present the error shown below.
* Host: Rocky 8.8
* Ledger not installed
* Git commit: [9afd519](https://github.com/ctrliq/ascender-install/commit/9afd519a040c6e5c6b4470c1ef989357762e4ecb)

```console
[root@ascender ascender-install]# ./setup.sh 
Using Inventory File: ./inventory
...
...
TASK [ascender_cleanup : Wait until Ascender API is Up] *********************************************************************
ok: [localhost]

TASK [ascender_cleanup : Disable the Next UI] *******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get token: HTTP Error 401: Unauthorized", "response": "{\"detail\":\"Authentication credentials were not provided. To establish a login session, visit /api/login/.\"}"}

PLAY RECAP ******************************************************************************************************************
ascender_host              : ok=11   changed=1    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
localhost                  : ok=25   changed=6    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   

ERROR OCCURRED DURING SETUP
```

**Comment by cigamit** [comment]
Thats an odd error.  What did you supply for
ASCENDER_ADMIN_USER
ASCENDER_ADMIN_PASSWORD

in your default.config.yaml?

**Comment by adamhgriffith-uofu** [comment]
Our credentials resembled:
```yaml
ASCENDER_ADMIN_USER: admin
ASCENDER_ADMIN_PASSWORD: "UPPERlower+["
```
If it helps, all Ascender-related pods are running, the web interface is being served, and I can successfully log into the web interface.

**Comment by michaelford85** [comment]
Adam:

I ran the installer with the target machine and installing machine being one and the same. While didn't recreate your issue, I am attaching my inventory and config (I matched your password) to see if you set up anything differently from me.[config.zip](https://github.com/ctrliq/ascender-install/files/12872018/config.zip)

**Comment by adamhgriffith-uofu** [comment]
@michaelford85,

Thank your for your help on this. Some differences on our end I should have mentioned earlier are:
```yaml
k8s_lb_protocol: https
tls_crt_path: "/etc/letsencrypt/live/ascender.our.domain/fullchain.pem"
tls_key_path: "/etc/letsencrypt/live/ascender.our.domain/privkey.pem"
use_etc_hosts: false

ASCENDER_HOSTNAME: ascender.our.domain
```

**Comment by cigamit** [comment]
I don't believe its the special characters in the password causing it, at least not directly.  I have ran the install 10 times with that password, and it failed twice but not the other 8 times.  I am thinking we are running into a race condition where something on the backend is not fully up, even though the api itself is returning fine when we check the ping (which doesn't require auth).  I am running a few more tests to see if I can pin it down.

**Comment by cigamit** [comment]
Even if it does fail, I can immediately rerun the cleanup playbook and it passes this time, so definitely not an issue with the password.

**Comment by cigamit** [comment]
ok, after many many hours of testing and debugging.  It does appear to be a race condition where the API service comes up before the uWSGI, nginx, or daphne services.  This would cause the ping to return because it doesn't require authentication, but anything else would fail.  

While debugging this, also found that if things were running really slow, even the database wasn't properly populated with the default items.

To combat both of these, we changed the API check to pull the id of the default organization instead.  This way, the API authentication has to be working, and the database has to be populated.
