### ISSUE TITLE
Add requirement of 8GB free space to /var directory when installing on k3s

### ISSUE THREAD

**Issue by friendlypenguin** [ctrliq/ascender-install#41]
When installing Ascender on k3s via setup.sh install script, the installation fails when there's not enough free space in the /var directory. It seems, that k3s downloads a lot of stuff to /var/lib/rancher. On Rocky9 just under 8GB free disk space was required for the installation to complete successfully.

Adding a note to the install documentation or adding an assert task would do the trick I guess.

**Comment by michaelford85** [comment]
@friendlypenguin Added an assertion for 20GB of free disk in playbooks/assertion.yml, and specified said requirement in the k3s README.

**Comment by michaelford85** [comment]
Closing this issue as the suggested changes have been made.
