### ISSUE TITLE
it can connects to ldap AD like Tower?

### ISSUE THREAD

**Issue by zikkuratti** [ctrliq/ascender-install#48]
it can connect's to ldap AD like Tower?

**Comment by adamhgriffith-uofu** [comment]
Yes. From Ascender's home page as an administrator, select **Settings** on the left side of the screen. On the page that appears you should see an **Authentication** panel with several available options, including LDAP.

![image](https://github.com/ctrliq/ascender-install/assets/94396076/6c25615f-91c4-4952-a846-c8368a7fdb09)
