### ISSUE TITLE
Issue with K3s - ~/.kube/config not found

### ISSUE THREAD

**Issue by kmf** [ctrliq/ascender-install#63]
https://github.com/ctrliq/ascender-install/blob/ed56d2200984e587b1fd6b90092a7caeaa1e1af4/playbooks/roles/k8s_setup/tasks/k8s_setup_k3s.yml#L45-L52

Had an issue here did a simple

```shell
mkdir ~/.kube/
cat /var/lib/rancher/k3s/server/cred/admin.kubeconfig >> ~/.kube/config
```

ps. I did run this is as `root` that could be the issue

**Comment by adamhgriffith-uofu** [comment]
Are you running the installer as `root`?
