### ISSUE TITLE
Self-signed certificate validation is not getting skipped in all the places

### ISSUE THREAD

**Issue by muralihcl** [ctrliq/ascender-install#85]
May have to include a new environment variable that can define if certificate validation needs to be set to false or true. That way, we can give the freedom of defining if certificate validation needs to be disabled for testing deployments. Had to face failure during installation because I didn't have a signed certificate.

**Comment by cigamit** [comment]
Where exactly did it fail?  I have several test boxes without valid certs.  It might be good to add an option though too, like you said.

**Comment by muralihcl** [comment]
Any playbook that has awx. collection being used would need that option to be set.

These two did not have validate_certs disabled.
playbooks/roles/ledger_install/tasks/ledger_install_k3s.yml
playbooks/roles/setup_playbooks/tasks/ascender_credentials_k3s.yml

These have already disabled the validate certs
playbooks/roles/setup_playbooks/tasks/inventories.yml
playbooks/roles/setup_playbooks/tasks/projects.yml
playbooks/roles/setup_playbooks/tasks/templates.yml

**Comment by cigamit** [comment]
Thanks.  I have resolved this now.  There were a few others that needed it also.
