### ISSUE TITLE
Despite installing ledger along with ascender, the logs are not getting sent to the ledger

### ISSUE THREAD

**Issue by muralihcl** [ctrliq/ascender-install#87]
Even though the ascender logging is configured to reach the ledger service using the admin credentials, I do not see the containers getting registered under the servers of ledger admin section, nor the logs are going out/reaching the ascender node.

![image](https://github.com/ctrliq/ascender-install/assets/39020854/2e19daba-3474-4135-9907-65b51f15466d)

The servers section from ledger shows nothing.

![image](https://github.com/ctrliq/ascender-install/assets/39020854/8c2783ee-e525-4f74-96b9-809e4fe2dbe2)

Saw rsyslogd misbehaving, but describe ascender-app-task pod says rsyslogd is running, but the log says otherwise.

![image](https://github.com/ctrliq/ascender-install/assets/39020854/50028aff-a835-44cf-ac67-bd63bd355c30)

**Comment by cigamit** [comment]
Since its using the internal IP on the cluster, try changing the URL to http instead of https.

**Comment by muralihcl** [comment]
By the way, how long it usually takes for ascender to send logs to the ledger?

<img width="771" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/132179d8-503d-460b-865c-430f7665cb42">

I ran setup module against 2 of the hosts in the inventory and it pulled all the facts. But, I do not see anything under facts or I don't see any of the servers being displayed under reports.

<img width="946" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/56120d0b-555e-451e-b688-59388742ac39">

<img width="942" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/c3c3657d-03be-4853-8f9b-e73d9a704768">

In ledger, both the ascender-app-web and ascender-app-task containers are pointing to https and not http. Is this expected?

<img width="375" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/e5e65724-f552-4119-9e8c-73653b7e83fe">


<img width="372" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/63e29366-5fb0-4f4b-afe5-3365634e8a0c">

**Comment by cigamit** [comment]
It should be instant. You might check the logs on the parser container and make sure there are no errors.  You show that the containers showed up in the Servers list, which means that logs have been sent and received by Ledger from Ascender, so we know something is at least getting there.

The Server Url is for the external link to the Ascender UI, so it would have no effect on receiving logs.  Its only useful when linking back into Ascender to directly view job runs there.

**Comment by cigamit** [comment]
Also something to double check, go into settings and ensure that gather_facts is an allowed module.  It should be by default.

**Comment by muralihcl** [comment]
That setting is there, without any changes.

<img width="315" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/3f99f615-b046-413a-b3cd-099b055d7174">

I even reinstalled with http and don't find the facts getting collected.

**Comment by muralihcl** [comment]
<img width="938" alt="rsyslog" src="https://github.com/ctrliq/ascender-install/assets/39020854/a1259eb6-1293-41c5-ac4e-6206c0a04a0c">

The only error I see is rsyslog error from ascender-app-task-7b9cc64f67-bm2rd pod. Seems like the issue still exists because of unresonsive rsyslogd itself

**Comment by muralihcl** [comment]
Any further suggestions?

**Comment by muralihcl** [comment]
An update, a complete new setup with HTTP just worked fine. Why isn't it working for HTTPS?

<img width="762" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/a17f5c9c-7337-4ab9-8966-499197fbe4f8">


<img width="779" alt="image" src="https://github.com/ctrliq/ascender-install/assets/39020854/620c29ee-5985-492d-853e-d1002f7e899e">

**Comment by michaelford85** [comment]
@muralihcl Where are you setting this up, meaning for what platform of Kubernetes? I will work to replicate it on my end.

**Comment by muralihcl** [comment]
I'm setting it up with K3s on Rocky Linux 8.9

**Comment by michaelford85** [comment]
@muralihcl - The ledger Web frontend (k8s service "web-svc") requires SSL authentication as it has an ingress object allowing external access. Ascender talks to the parser service, which is not fronted by an Ingres object and does not require SSL certificates. In the logging section of Ascender you still need the username and password for ledger, but can set the Logging Aggregator URL to "http://<parser service address>".

**Comment by cigamit** [comment]
>  In the logging section of Ascender you still need the username and password for ledger, but can set the Logging Aggregator URL to "http://[parser service address]".

You don't need the username and password set, its currently unused if set.  We instead require you to trust the server in the admin section instead before it will allow any logs from it.
