### ISSUE TITLE
ascender_operator_version being set to ascender version in config_vars 

### ISSUE THREAD

**Issue by ssimpson89** [ctrliq/ascender-install#88]
When you manually type in an ascender operator version and a version or ascender the setup script will choose the ascender version tag as the ascender operator tag causing a failure to deploy

```
# The image tag indicating the version of Ascender you wish to install
ASCENDER_VERSION: 24.0.1
# The version of the AWX Operator used to install Ascender and its components
ANSIBLE_OPERATOR_VERSION: 24.0.1
```

**Comment by cigamit** [comment]
Can you rebase this against devel?

**Comment by ssimpson89** [comment]
I just resubmitted a new pull request into devel. Let me know if that is what you need

**Comment by cigamit** [comment]
Thanks.  This has been merged.  I will get everything over into main shortly.
